quotas:
  - managed-kubernetes.clusters.count
  - managed-kubernetes.cores.count
  - managed-kubernetes.disk.size
  - managed-kubernetes.nodeGroups.count
  - managed-kubernetes.nodes.count
  - managed-kubernetes.memory.size
