roles:

  infra.onCall:
    name: infra.onCallAdmin
    groups: [infra]
    description: Infra on-call
    visibility: internal
    includedRoles:
      - onCall
      - compute.onCall

  infra.onCallAdmin:
    name: infra.onCallAdmin
    groups: [infra]
    description: Infra on-call Admin
    visibility: internal
    includedRoles:
      - infra.onCall
      - compute.onCallAdmin
    permissions:
      - nbsInternal.disks.update
      - nbsInternal.disks.write
