p { i: "dpdk" x: "e1000_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/e1000/base" }
p { i: "dpdk" x: "fm10k_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/fm10k/base" }
p { i: "dpdk" x: "hinic_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/hinic/base" }
p { i: "dpdk" x: "i40e_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/i40e/base" }
p { i: "dpdk" x: "ice_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ice/base" }
p { i: "dpdk" x: "igc_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/igc/base" }
p { i: "dpdk" x: "ixgbe_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ixgbe/base" }
p { i: "dpdk" x: "nicvf_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/thunderx/base" }
p { i: "dpdk" x: "octeontx_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/octeontx/base" }
p { i: "dpdk" x: "qede_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/qede/base" }
p { i: "dpdk" x: "rte_acl" ix: true peerdir: "contrib/libs/dpdk/lib/librte_acl" }
p { i: "dpdk" x: "rte_baseband_acc100" ix: true peerdir: "contrib/libs/dpdk/drivers/baseband/acc100" }
p { i: "dpdk" x: "rte_baseband_fpga_5gnr_fec" ix: true peerdir: "contrib/libs/dpdk/drivers/baseband/fpga_5gnr_fec" }
p { i: "dpdk" x: "rte_baseband_fpga_lte_fec" ix: true peerdir: "contrib/libs/dpdk/drivers/baseband/fpga_lte_fec" }
p { i: "dpdk" x: "rte_baseband_null" ix: true peerdir: "contrib/libs/dpdk/drivers/baseband/null" }
p { i: "dpdk" x: "rte_baseband_turbo_sw" ix: true peerdir: "contrib/libs/dpdk/drivers/baseband/turbo_sw" }
p { i: "dpdk" x: "rte_bbdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_bbdev" }
p { i: "dpdk" x: "rte_bitratestats" ix: true peerdir: "contrib/libs/dpdk/lib/librte_bitratestats" }
p { i: "dpdk" x: "rte_bpf" ix: true peerdir: "contrib/libs/dpdk/lib/librte_bpf" }
p { i: "dpdk" x: "rte_bus_dpaa" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/dpaa" }
p { i: "dpdk" x: "rte_bus_fslmc" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/fslmc" }
p { i: "dpdk" x: "rte_bus_ifpga" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/ifpga" }
p { i: "dpdk" x: "rte_bus_pci" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/pci" }
p { i: "dpdk" x: "rte_bus_vdev" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/vdev" }
p { i: "dpdk" x: "rte_bus_vmbus" ix: true peerdir: "contrib/libs/dpdk/drivers/bus/vmbus" }
p { i: "dpdk" x: "rte_cfgfile" ix: true peerdir: "contrib/libs/dpdk/lib/librte_cfgfile" }
p { i: "dpdk" x: "rte_cmdline" ix: true peerdir: "contrib/libs/dpdk/lib/librte_cmdline" }
p { i: "dpdk" x: "rte_common_cpt" ix: true peerdir: "contrib/libs/dpdk/drivers/common/cpt" }
p { i: "dpdk" x: "rte_common_dpaax" ix: true peerdir: "contrib/libs/dpdk/drivers/common/dpaax" }
p { i: "dpdk" x: "rte_common_iavf" ix: true peerdir: "contrib/libs/dpdk/drivers/common/iavf" }
p { i: "dpdk" x: "rte_common_mlx5" ix: true peerdir: "contrib/libs/dpdk/drivers/common/mlx5" }
p { i: "dpdk" x: "rte_common_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/common/octeontx" }
p { i: "dpdk" x: "rte_common_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/common/octeontx2" }
p { i: "dpdk" x: "rte_common_qat" ix: true peerdir: "contrib/libs/dpdk/drivers/common/qat" }
p { i: "dpdk" x: "rte_common_sfc_efx" ix: true peerdir: "contrib/libs/dpdk/drivers/common/sfc_efx" }
p { i: "dpdk" x: "rte_compress_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/compress/octeontx" }
p { i: "dpdk" x: "rte_compressdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_compressdev" }
p { i: "dpdk" x: "rte_crypto_bcmfs" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/bcmfs" }
p { i: "dpdk" x: "rte_crypto_caam_jr" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/caam_jr" }
p { i: "dpdk" x: "rte_crypto_dpaa2_sec" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/dpaa2_sec" }
p { i: "dpdk" x: "rte_crypto_dpaa_sec" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/dpaa_sec" }
p { i: "dpdk" x: "rte_crypto_nitrox" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/nitrox" }
p { i: "dpdk" x: "rte_crypto_null" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/null" }
p { i: "dpdk" x: "rte_crypto_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/octeontx" }
p { i: "dpdk" x: "rte_crypto_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/octeontx2" }
p { i: "dpdk" x: "rte_crypto_scheduler" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/scheduler" }
p { i: "dpdk" x: "rte_crypto_virtio" ix: true peerdir: "contrib/libs/dpdk/drivers/crypto/virtio" }
p { i: "dpdk" x: "rte_cryptodev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_cryptodev" }
p { i: "dpdk" x: "rte_distributor" ix: true peerdir: "contrib/libs/dpdk/lib/librte_distributor" }
p { i: "dpdk" x: "rte_eal" ix: true peerdir: "contrib/libs/dpdk/lib/librte_eal" }
p { i: "dpdk" x: "rte_efd" ix: true peerdir: "contrib/libs/dpdk/lib/librte_efd" }
p { i: "dpdk" x: "rte_ethdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_ethdev" }
p { i: "dpdk" x: "rte_event_dlb" ix: true peerdir: "contrib/libs/dpdk/drivers/event/dlb" }
p { i: "dpdk" x: "rte_event_dlb2" ix: true peerdir: "contrib/libs/dpdk/drivers/event/dlb2" }
p { i: "dpdk" x: "rte_event_dpaa" ix: true peerdir: "contrib/libs/dpdk/drivers/event/dpaa" }
p { i: "dpdk" x: "rte_event_dpaa2" ix: true peerdir: "contrib/libs/dpdk/drivers/event/dpaa2" }
p { i: "dpdk" x: "rte_event_dsw" ix: true peerdir: "contrib/libs/dpdk/drivers/event/dsw" }
p { i: "dpdk" x: "rte_event_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/event/octeontx" }
p { i: "dpdk" x: "rte_event_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/event/octeontx2" }
p { i: "dpdk" x: "rte_event_opdl" ix: true peerdir: "contrib/libs/dpdk/drivers/event/opdl" }
p { i: "dpdk" x: "rte_event_skeleton" ix: true peerdir: "contrib/libs/dpdk/drivers/event/skeleton" }
p { i: "dpdk" x: "rte_event_sw" ix: true peerdir: "contrib/libs/dpdk/drivers/event/sw" }
p { i: "dpdk" x: "rte_eventdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_eventdev" }
p { i: "dpdk" x: "rte_fib" ix: true peerdir: "contrib/libs/dpdk/lib/librte_fib" }
p { i: "dpdk" x: "rte_flow_classify" ix: true peerdir: "contrib/libs/dpdk/lib/librte_flow_classify" }
p { i: "dpdk" x: "rte_graph" ix: true peerdir: "contrib/libs/dpdk/lib/librte_graph" }
p { i: "dpdk" x: "rte_gro" ix: true peerdir: "contrib/libs/dpdk/lib/librte_gro" }
p { i: "dpdk" x: "rte_gso" ix: true peerdir: "contrib/libs/dpdk/lib/librte_gso" }
p { i: "dpdk" x: "rte_hash" ix: true peerdir: "contrib/libs/dpdk/lib/librte_hash" }
p { i: "dpdk" x: "rte_ip_frag" ix: true peerdir: "contrib/libs/dpdk/lib/librte_ip_frag" }
p { i: "dpdk" x: "rte_ipsec" ix: true peerdir: "contrib/libs/dpdk/lib/librte_ipsec" }
p { i: "dpdk" x: "rte_jobstats" ix: true peerdir: "contrib/libs/dpdk/lib/librte_jobstats" }
p { i: "dpdk" x: "rte_kni" ix: true peerdir: "contrib/libs/dpdk/lib/librte_kni" }
p { i: "dpdk" x: "rte_kvargs" ix: true peerdir: "contrib/libs/dpdk/lib/librte_kvargs" }
p { i: "dpdk" x: "rte_latencystats" ix: true peerdir: "contrib/libs/dpdk/lib/librte_latencystats" }
p { i: "dpdk" x: "rte_lpm" ix: true peerdir: "contrib/libs/dpdk/lib/librte_lpm" }
p { i: "dpdk" x: "rte_mbuf" ix: true peerdir: "contrib/libs/dpdk/lib/librte_mbuf" }
p { i: "dpdk" x: "rte_member" ix: true peerdir: "contrib/libs/dpdk/lib/librte_member" }
p { i: "dpdk" x: "rte_mempool" ix: true peerdir: "contrib/libs/dpdk/lib/librte_mempool" }
p { i: "dpdk" x: "rte_mempool_bucket" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/bucket" }
p { i: "dpdk" x: "rte_mempool_dpaa" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/dpaa" }
p { i: "dpdk" x: "rte_mempool_dpaa2" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/dpaa2" }
p { i: "dpdk" x: "rte_mempool_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/octeontx" }
p { i: "dpdk" x: "rte_mempool_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/octeontx2" }
p { i: "dpdk" x: "rte_mempool_ring" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/ring" }
p { i: "dpdk" x: "rte_mempool_stack" ix: true peerdir: "contrib/libs/dpdk/drivers/mempool/stack" }
p { i: "dpdk" x: "rte_meter" ix: true peerdir: "contrib/libs/dpdk/lib/librte_meter" }
p { i: "dpdk" x: "rte_metrics" ix: true peerdir: "contrib/libs/dpdk/lib/librte_metrics" }
p { i: "dpdk" x: "rte_net" ix: true peerdir: "contrib/libs/dpdk/lib/librte_net" }
p { i: "dpdk" x: "rte_net_af_packet" ix: true peerdir: "contrib/libs/dpdk/drivers/net/af_packet" }
p { i: "dpdk" x: "rte_net_ark" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ark" }
p { i: "dpdk" x: "rte_net_atlantic" ix: true peerdir: "contrib/libs/dpdk/drivers/net/atlantic" }
p { i: "dpdk" x: "rte_net_avp" ix: true peerdir: "contrib/libs/dpdk/drivers/net/avp" }
p { i: "dpdk" x: "rte_net_axgbe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/axgbe" }
p { i: "dpdk" x: "rte_net_bnxt" ix: true peerdir: "contrib/libs/dpdk/drivers/net/bnxt" }
p { i: "dpdk" x: "rte_net_bond" ix: true peerdir: "contrib/libs/dpdk/drivers/net/bonding" }
p { i: "dpdk" x: "rte_net_cxgbe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/cxgbe" }
p { i: "dpdk" x: "rte_net_dpaa" ix: true peerdir: "contrib/libs/dpdk/drivers/net/dpaa" }
p { i: "dpdk" x: "rte_net_dpaa2" ix: true peerdir: "contrib/libs/dpdk/drivers/net/dpaa2" }
p { i: "dpdk" x: "rte_net_e1000" ix: true peerdir: "contrib/libs/dpdk/drivers/net/e1000" }
p { i: "dpdk" x: "rte_net_ena" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ena" }
p { i: "dpdk" x: "rte_net_enetc" ix: true peerdir: "contrib/libs/dpdk/drivers/net/enetc" }
p { i: "dpdk" x: "rte_net_enic" ix: true peerdir: "contrib/libs/dpdk/drivers/net/enic" }
p { i: "dpdk" x: "rte_net_failsafe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/failsafe" }
p { i: "dpdk" x: "rte_net_fm10k" ix: true peerdir: "contrib/libs/dpdk/drivers/net/fm10k" }
p { i: "dpdk" x: "rte_net_hinic" ix: true peerdir: "contrib/libs/dpdk/drivers/net/hinic" }
p { i: "dpdk" x: "rte_net_hns3" ix: true peerdir: "contrib/libs/dpdk/drivers/net/hns3" }
p { i: "dpdk" x: "rte_net_i40e" ix: true peerdir: "contrib/libs/dpdk/drivers/net/i40e" }
p { i: "dpdk" x: "rte_net_iavf" ix: true peerdir: "contrib/libs/dpdk/drivers/net/iavf" }
p { i: "dpdk" x: "rte_net_ice" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ice" }
p { i: "dpdk" x: "rte_net_igc" ix: true peerdir: "contrib/libs/dpdk/drivers/net/igc" }
p { i: "dpdk" x: "rte_net_ixgbe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ixgbe" }
p { i: "dpdk" x: "rte_net_kni" ix: true peerdir: "contrib/libs/dpdk/drivers/net/kni" }
p { i: "dpdk" x: "rte_net_liquidio" ix: true peerdir: "contrib/libs/dpdk/drivers/net/liquidio" }
p { i: "dpdk" x: "rte_net_memif" ix: true peerdir: "contrib/libs/dpdk/drivers/net/memif" }
p { i: "dpdk" x: "rte_net_mlx5" ix: true peerdir: "contrib/libs/dpdk/drivers/net/mlx5" }
p { i: "dpdk" x: "rte_net_netvsc" ix: true peerdir: "contrib/libs/dpdk/drivers/net/netvsc" }
p { i: "dpdk" x: "rte_net_nfp" ix: true peerdir: "contrib/libs/dpdk/drivers/net/nfp" }
p { i: "dpdk" x: "rte_net_null" ix: true peerdir: "contrib/libs/dpdk/drivers/net/null" }
p { i: "dpdk" x: "rte_net_octeontx" ix: true peerdir: "contrib/libs/dpdk/drivers/net/octeontx" }
p { i: "dpdk" x: "rte_net_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/net/octeontx2" }
p { i: "dpdk" x: "rte_net_pfe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/pfe" }
p { i: "dpdk" x: "rte_net_qede" ix: true peerdir: "contrib/libs/dpdk/drivers/net/qede" }
p { i: "dpdk" x: "rte_net_ring" ix: true peerdir: "contrib/libs/dpdk/drivers/net/ring" }
p { i: "dpdk" x: "rte_net_sfc" ix: true peerdir: "contrib/libs/dpdk/drivers/net/sfc" }
p { i: "dpdk" x: "rte_net_softnic" ix: true peerdir: "contrib/libs/dpdk/drivers/net/softnic" }
p { i: "dpdk" x: "rte_net_tap" ix: true peerdir: "contrib/libs/dpdk/drivers/net/tap" }
p { i: "dpdk" x: "rte_net_thunderx" ix: true peerdir: "contrib/libs/dpdk/drivers/net/thunderx" }
p { i: "dpdk" x: "rte_net_txgbe" ix: true peerdir: "contrib/libs/dpdk/drivers/net/txgbe" }
p { i: "dpdk" x: "rte_net_vdev_netvsc" ix: true peerdir: "contrib/libs/dpdk/drivers/net/vdev_netvsc" }
p { i: "dpdk" x: "rte_net_vhost" ix: true peerdir: "contrib/libs/dpdk/drivers/net/vhost" }
p { i: "dpdk" x: "rte_net_virtio" ix: true peerdir: "contrib/libs/dpdk/drivers/net/virtio" }
p { i: "dpdk" x: "rte_net_vmxnet3" ix: true peerdir: "contrib/libs/dpdk/drivers/net/vmxnet3" }
p { i: "dpdk" x: "rte_node" ix: true peerdir: "contrib/libs/dpdk/lib/librte_node" }
p { i: "dpdk" x: "rte_pci" ix: true peerdir: "contrib/libs/dpdk/lib/librte_pci" }
p { i: "dpdk" x: "rte_pdump" ix: true peerdir: "contrib/libs/dpdk/lib/librte_pdump" }
p { i: "dpdk" x: "rte_pipeline" ix: true peerdir: "contrib/libs/dpdk/lib/librte_pipeline" }
p { i: "dpdk" x: "rte_port" ix: true peerdir: "contrib/libs/dpdk/lib/librte_port" }
p { i: "dpdk" x: "rte_power" ix: true peerdir: "contrib/libs/dpdk/lib/librte_power" }
p { i: "dpdk" x: "rte_raw_dpaa2_cmdif" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/dpaa2_cmdif" }
p { i: "dpdk" x: "rte_raw_dpaa2_qdma" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/dpaa2_qdma" }
p { i: "dpdk" x: "rte_raw_ioat" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/ioat" }
p { i: "dpdk" x: "rte_raw_ntb" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/ntb" }
p { i: "dpdk" x: "rte_raw_octeontx2_dma" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/octeontx2_dma" }
p { i: "dpdk" x: "rte_raw_octeontx2_ep" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/octeontx2_ep" }
p { i: "dpdk" x: "rte_raw_skeleton" ix: true peerdir: "contrib/libs/dpdk/drivers/raw/skeleton" }
p { i: "dpdk" x: "rte_rawdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_rawdev" }
p { i: "dpdk" x: "rte_rcu" ix: true peerdir: "contrib/libs/dpdk/lib/librte_rcu" }
p { i: "dpdk" x: "rte_regex_mlx5" ix: true peerdir: "contrib/libs/dpdk/drivers/regex/mlx5" }
p { i: "dpdk" x: "rte_regex_octeontx2" ix: true peerdir: "contrib/libs/dpdk/drivers/regex/octeontx2" }
p { i: "dpdk" x: "rte_regexdev" ix: true peerdir: "contrib/libs/dpdk/lib/librte_regexdev" }
p { i: "dpdk" x: "rte_reorder" ix: true peerdir: "contrib/libs/dpdk/lib/librte_reorder" }
p { i: "dpdk" x: "rte_rib" ix: true peerdir: "contrib/libs/dpdk/lib/librte_rib" }
p { i: "dpdk" x: "rte_ring" ix: true peerdir: "contrib/libs/dpdk/lib/librte_ring" }
p { i: "dpdk" x: "rte_sched" ix: true peerdir: "contrib/libs/dpdk/lib/librte_sched" }
p { i: "dpdk" x: "rte_security" ix: true peerdir: "contrib/libs/dpdk/lib/librte_security" }
p { i: "dpdk" x: "rte_stack" ix: true peerdir: "contrib/libs/dpdk/lib/librte_stack" }
p { i: "dpdk" x: "rte_table" ix: true peerdir: "contrib/libs/dpdk/lib/librte_table" }
p { i: "dpdk" x: "rte_telemetry" ix: true peerdir: "contrib/libs/dpdk/lib/librte_telemetry" }
p { i: "dpdk" x: "rte_timer" ix: true peerdir: "contrib/libs/dpdk/lib/librte_timer" }
p { i: "dpdk" x: "rte_vdpa_ifc" ix: true peerdir: "contrib/libs/dpdk/drivers/vdpa/ifc" }
p { i: "dpdk" x: "rte_vdpa_mlx5" ix: true peerdir: "contrib/libs/dpdk/drivers/vdpa/mlx5" }
p { i: "dpdk" x: "rte_vhost" ix: true peerdir: "contrib/libs/dpdk/lib/librte_vhost" }
p { i: "dpdk" x: "sfc_base" ix: true peerdir: "contrib/libs/dpdk/drivers/common/sfc_efx/base" }
p { i: "dpdk" x: "txgbe_base" ix: true peerdir: "contrib/libs/dpdk/drivers/net/txgbe/base" }
p { x: "dpdk-testpmd" peerdir: "contrib/libs/dpdk/app/test-pmd" }
